app:
  title: FastAPI
  version: 0.1.0
  host: 127.0.0.1
  port: 8000
  reload: True
  timeout: 1.5

weather:
  base_url: https://thirdparty-weather-api-v2.droom.workers.dev
  historical_endpoint: /historical/hourly
  current_endpoint: /current
  api_key: CMRJW4WT7V3QA5AOIGPBC
  weather_map:
    - "sun"
    - "smoke"
    - "rain"
    - "snow"
    - "others"
